config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root"application#index"
  resources :restaurants, only: [:index, :show] do
  	resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    get :feeds, :on => :collection
    get :experts, :on => :collection
    member do
      post :like
      post :unlike
    end
  end
  resources :categories, only: [:show]
  resources :users, only: [:index, :show, :edit, :update]
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  namespace :admin do
  	resources :restaurants
  	resources :categories
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	validates_presence_of(:name,:tel,:address,:opening_hours)
	mount_uploader :image, PhotoUploader
	belongs_to :category
	#喜歡、收藏餐廳 （刪除餐廳時會刪除喜歡的紀錄）
	has_many :favorites, dependent: :destroy
	#留言
	has_many :comments, dependent: :destroy
	#喜歡
	has_many :likes, dependent: :destroy
	has_many :liked_users, through: :likes, source: :user

	def rank_count
		#rank由 favorite 跟 like 相加，之後也可以加入comment
		count=self.favorites.size
		count=count+self.likes.size
		#count=count+self.comments.size
		self.rank=count
		self.save
	end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

	def index
		@all_restaurants=Restaurant.page(params[:page]).per(10)
	end

	def new
		@new_restaurant=Restaurant.new
	end

  def show
    @the_restaurant=Restaurant.find(params[:id])
  end

	def create
    @new_restaurant = Restaurant.new(restaurant_params) #實例變數必須和new相同，這樣才能回傳error訊息回去render
    if @new_restaurant.save
      flash[:notice] = "(notice)新增成功"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "(alert)新增失敗"
      render :new
    end
  end

  def edit #實例變數必須和new相同(使用相同的partial form)
    @new_restaurant=Restaurant.find(params[:id])
  end

  def update #實例變數必須和new相同(使用相同的partial form)
    @new_restaurant = Restaurant.find(params[:id])
    if @new_restaurant.update(restaurant_params)
      flash[:notice] = "(notice)更新成功"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "(alert)更新失敗"
      render :edit
    end
  end

  def destroy
    @find_restaurant = Restaurant.find(params[:id])
    if @find_restaurant.destroy
      flash[:notice] = "(notice)刪除成功"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "(alert)刪除失敗"
      render :edit
    end
end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants=Restaurant.page(params[:page]).per(9)
    @categories=Category.all
  end
  def show
    @restaurant = Restaurant.find(params[:id])
    @favorite=Favorite.where( :restaurant_id => @restaurant, :user_id => current_user )
    @comment = Comment.new
    if current_user.restaurants.exists?(:id => params[:id])
      @favorite_check=:True
    else
      @favorite_check=:False
    end
  end
  def feeds
    @categories=Category.all
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
    @ranks = Restaurant.order(rank: :desc).limit(10)
  end
  def experts
    @categories=Category.all
    @most_comments=User.joins(:comments).group("users.id").order("count(users.id) DESC").limit(10)
    @most_followers=User.joins(:followers).group("users.id").order("count(users.id) DESC").limit(10)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    @restaurant.rank_count
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end
  def unlike
    @restaurant = Restaurant.find(params[:id])
    like = Like.where(restaurant: @restaurant, user: current_user)
    like.destroy_all
    @restaurant.rank_count
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/views/admin/restaurants/_form.html.erb
<%= form_for  [:admin, @new_restaurant] do |r| %>
  <%= r.label :name, "餐廳名字" %>
  <%= r.text_field :name %>

  <%= r.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>

  <%= r.label :tel, "聯絡電話" %>
  <%= r.text_field :tel %>

  <%= r.label :address, "地址" %>
  <%= r.text_field :address %>

  <%= r.label :opening_hours, "營業時間" %>
  <%= r.text_field :opening_hours %>

  <%= r.label :description, "餐廳簡介" %>
  <%= r.text_area :description %>

  <%= r.label :image, "上傳照片" %>
  <%= image_tag @new_restaurant.image,width:'300px' if @new_restaurant.image? %>
  <%= r.file_field :image %>

  <%= r.submit %>
<% end %>

app/views/admin/restaurants/edit.html.erb
<h1>admin 編輯餐廳</h1>

<% if @new_restaurant.errors.any? %>
<h2>錯誤訊息(<%= @new_restaurant.errors.full_messages %>)</h2>
<ul>
<% @new_restaurant.errors.full_messages.each do |m| %>
<li><%= m %></li>
<% end %>
</ul>
<% end %>

<%= render partial:"form" %>

app/views/admin/restaurants/index.html.erb
  <h1>admin後台</h1>
  <div class="margin-10-10">
    <%= link_to 'Restaurant', admin_restaurants_path %> |
    <%= link_to 'Categories', admin_categories_path %>
  </div>
  <div class="margin-10-10">
    <%= link_to '新增',new_admin_restaurant_path %>
  </div>

  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Category</th>
            <th>Name</th>
            <th>Function</th>
          </tr>
        </thead>
        <tbody>
          <% @all_restaurants.each do |restaurant| %>
          <tr>
            <td><%= restaurant.id %></td>
            <td>[<%= restaurant.category.name %>]</td>
            <td><%= restaurant.name %></td>
            <td>
              <%= link_to 'Show', admin_restaurant_path(restaurant) %>
              <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
              <%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  
  <div class="margin-10-10">
    <%= paginate @all_restaurants %>
  </div>
  <div style="height: 1px;"></div>

app/views/admin/restaurants/new.html.erb
<h1>admin 新增餐廳 </h1>

<% if @new_restaurant.errors.any? %> 
<!-- #好像不能用partial form  -->
<h2>錯誤訊息(<%= @new_restaurant.errors.full_messages %>)</h2>
<ul>
<% @new_restaurant.errors.full_messages.each do |m| %>
<li><%= m %></li>
<% end %>
</ul>
<% end %>

<%= render partial:"form" %>

app/views/admin/restaurants/show.html.erb
<h1>admin show</h1>
<%= @the_restaurant.name %>
<%= image_tag @the_restaurant.image,width:'300px' if @the_restaurant.image? %>