config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root"application#index"
  resources :restaurants, only: [:index, :show] do
  	resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    get :feeds, :on => :collection
    get :experts, :on => :collection
    member do
      post :like
      post :unlike
    end
  end
  resources :categories, only: [:show]
  resources :users, only: [:index, :show, :edit, :update]
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  namespace :admin do
  	resources :restaurants
  	resources :categories
  end

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	validates_presence_of(:name,:tel,:address,:opening_hours)
	mount_uploader :image, PhotoUploader
	belongs_to :category
	#喜歡、收藏餐廳 （刪除餐廳時會刪除喜歡的紀錄）
	has_many :favorites, dependent: :destroy
	#留言
	has_many :comments, dependent: :destroy
	#喜歡
	has_many :likes, dependent: :destroy
	has_many :liked_users, through: :likes, source: :user

	def rank_count
		#rank由 favorite 跟 like 相加，之後也可以加入comment
		count=self.favorites.size
		count=count+self.likes.size
		#count=count+self.comments.size
		self.rank=count
		self.save
	end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

	def index
		@all_restaurants=Restaurant.page(params[:page]).per(10)
	end

	def new
		@new_restaurant=Restaurant.new
	end

  def show
    @the_restaurant=Restaurant.find(params[:id])
  end

	def create
    @new_restaurant = Restaurant.new(restaurant_params) #實例變數必須和new相同，這樣才能回傳error訊息回去render
    if @new_restaurant.save
      flash[:notice] = "(notice)新增成功"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "(alert)新增失敗"
      render :new
    end
  end

  def edit #實例變數必須和new相同(使用相同的partial form)
    @new_restaurant=Restaurant.find(params[:id])
  end

  def update #實例變數必須和new相同(使用相同的partial form)
    @new_restaurant = Restaurant.find(params[:id])
    if @new_restaurant.update(restaurant_params)
      flash[:notice] = "(notice)更新成功"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "(alert)更新失敗"
      render :edit
    end
  end

  def destroy
    @find_restaurant = Restaurant.find(params[:id])
    if @find_restaurant.destroy
      flash[:notice] = "(notice)刪除成功"
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "(alert)刪除失敗"
      render :edit
    end
end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants=Restaurant.page(params[:page]).per(9)
    @categories=Category.all
  end
  def show
    @restaurant = Restaurant.find(params[:id])
    @favorite=Favorite.where( :restaurant_id => @restaurant, :user_id => current_user )
    @comment = Comment.new
    if current_user.restaurants.exists?(:id => params[:id])
      @favorite_check=:True
    else
      @favorite_check=:False
    end
  end
  def feeds
    @categories=Category.all
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
    @ranks = Restaurant.order(rank: :desc).limit(10)
  end
  def experts
    @categories=Category.all
    @most_comments=User.joins(:comments).group("users.id").order("count(users.id) DESC").limit(10)
    @most_followers=User.joins(:followers).group("users.id").order("count(users.id) DESC").limit(10)
  end

  def like
    @restaurant = Restaurant.find(params[:id])
    @restaurant.likes.create!(user: current_user)
    @restaurant.rank_count
    redirect_back(fallback_location: root_path)  # 導回上一頁
  end
  def unlike
    @restaurant = Restaurant.find(params[:id])
    like = Like.where(restaurant: @restaurant, user: current_user)
    like.destroy_all
    @restaurant.rank_count
    redirect_back(fallback_location: root_path)
  end
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/views/restaurants/experts.html.erb
  <div class="tab-bar">
    <ul class="nav nav-tabs nav-tabs-main">
      <li class="nav-item">
        <%= link_to "所有餐廳", restaurants_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "餐廳分類", category_path(@categories.first), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "最新動態", feeds_restaurants_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "美食達人", experts_restaurants_path, class: "active nav-link" %>
      </li>
    </ul>
  </div>

<div class="row">
  <div class="col-lg-4 col-sm-10">
    <h3>最多追蹤</h3>
    <% @most_followers.each do |u| %>
      <div class="experts-block">
        <div class="row">
          <div class="col-lg-6 col-sm-10">
            <div class="experts-pic-height">
              <%= link_to image_tag(u.avatar, {alt: "image-not-found", onerror:"this.src='/image-not-found.jpg';", class:"experts-pic-fit img-fluid mb-3 mb-lg-0 rounded"}), user_path(u), {class:"experts-pic-position"} %>
            </div>
          </div>
          <div class="col-lg-6 col-sm-10">
            <div class="experts-name">
                <p><%= u.name %></p>
                <%if not u==current_user %>
                  <%if current_user.followings.exists?(:id => u.id) %>
                    <%= link_to "取消追蹤！", followship_path(u), {method: :delete, class:"btn btn-secondary btn-sm"} %>
                  <%else%>
                    <%= link_to "追蹤達人！", followships_path(following_id: u), {method: :post, class:"btn btn-info btn-sm"} %>
                  <%end%>
                <% else %>
                  <%= link_to "編輯", edit_user_registration_path, {method: :get, class:"btn btn-primary btn-sm"} %>
                <%end%>
            </div>
          </div>
        </div>
        <div class="experts-intro">
          <p><%= u.intro %><br>粉絲人數：<%= u.followers.size%></p>
        </div>
      </div>
    <% end %> 
  </div>

    <div class="col-lg-4 col-sm-10">
    <h3>最多留言</h3>
    <% @most_comments.each do |u| %>
      <div class="experts-block">
        <div class="row">
          <div class="col-lg-6 col-sm-10">
            <div class="experts-pic-height">
              <%= link_to image_tag(u.avatar, {alt: "image-not-found", onerror:"this.src='/image-not-found.jpg';", class:"experts-pic-fit img-fluid mb-3 mb-lg-0 rounded"}), user_path(u), {class:"experts-pic-position"} %>
            </div>
          </div>
          <div class="col-lg-6 col-sm-10">
            <div class="experts-name">
                <p><%= u.name %></p>
                <%if not u==current_user %>
                  <%if current_user.followings.exists?(:id => u.id) %>
                    <%= link_to "取消追蹤！", followship_path(u), {method: :delete, class:"btn btn-secondary btn-sm"} %>
                  <%else%>
                    <%= link_to "追蹤達人！", followships_path(following_id: u), {method: :post, class:"btn btn-info btn-sm"} %>
                  <%end%>
                <% else %>
                  <%= link_to "編輯", edit_user_registration_path, {method: :get, class:"btn btn-primary btn-sm"} %>
                <%end%>
            </div>
          </div>
        </div>
        <div class="experts-intro">
          <p><%= u.intro %><br>留言次數：<%= u.comments.size%></p>
        </div>
      </div>
    <% end %> 
  </div>

  <div class="col-lg-4 col-sm-10">
    <h3>最多好友（建置中）</h3>
  </div>

</div>

app/views/restaurants/feeds.html.erb
  <div class="tab-bar">
    <ul class="nav nav-tabs nav-tabs-main">
      <li class="nav-item">
        <%= link_to "所有餐廳", restaurants_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "餐廳分類", category_path(@categories.first), class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "最新動態", feeds_restaurants_path, class: "active nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "美食達人", experts_restaurants_path, class: "nav-link" %>
      </li>
    </ul>
  </div>

<div class="row">
  <div class="col-lg-4 col-sm-10">
    <h3>最新餐廳</h3>
    <% @recent_restaurants.each do |restaurant| %>
      <div class="feeds-block">
        <div class="row">
          <div class="col-lg-6 col-sm-10">
            <div class="feeds-pic-height">
              <%= link_to image_tag(restaurant.image, {alt: "image-not-found", onerror:"this.src='/image-not-found.jpg';", class:"feeds-pic-fit img-fluid mb-3 mb-lg-0 rounded"}), restaurant_path(restaurant), {class:"feeds-pic-position"} %>
            </div>
          </div>
          <div class="col-lg-6 col-sm-10">
            <div class="feeds-name">
                <p><%= restaurant.name %></p>
                <%if current_user.restaurants.exists?(:id => restaurant.id)%>
                <%= link_to "取消最愛", restaurant_favorite_path(restaurant, Favorite.where(:user_id=>current_user.id,:restaurant_id => restaurant.id)), {method: :delete, class:"btn btn-secondary btn-sm"} %>
                <%else%>
                <%= link_to "加入最愛", restaurant_favorites_path(restaurant), {method: :post, class:"btn btn-info btn-sm"} %>
                <%end%>
                <%if restaurant.liked_users.include?(current_user) %>
                <%= link_to "取消追蹤", unlike_restaurant_path(restaurant), {method: :post, class:"btn btn-secondary btn-sm"} %>
                <%else %>
                <%= link_to "追蹤", like_restaurant_path(restaurant), {method: :post, class:"btn btn-info btn-sm"} %>
                <%end%>
            </div>
          </div>
        </div>
        <div class="feeds-intro">
          <p><%= restaurant.description %></p>
        </div>
      </div>
    <% end %> 
  </div>

  <div class="col-lg-4 col-sm-10">
    <h3>熱門餐廳</h3>
    <% @ranks.each do |restaurant| %>
      <div class="feeds-block">
        <div class="row">
          <div class="col-lg-6 col-sm-10">
            <div class="feeds-pic-height">
              <%= link_to image_tag(restaurant.image, {alt: "image-not-found", onerror:"this.src='/image-not-found.jpg';", class:"feeds-pic-fit img-fluid mb-3 mb-lg-0 rounded"}), restaurant_path(restaurant), {class:"feeds-pic-position"} %>
            </div>
          </div>
          <div class="col-lg-6 col-sm-10">
            <div class="feeds-name">
                <p><%= restaurant.name %></p>
                <%if current_user.restaurants.exists?(:id => restaurant.id)%>
                <%= link_to "取消最愛", restaurant_favorite_path(restaurant, Favorite.where(:user_id=>current_user.id,:restaurant_id => restaurant.id)), {method: :delete, class:"btn btn-secondary btn-sm"} %>
                <%else%>
                <%= link_to "加入最愛", restaurant_favorites_path(restaurant), {method: :post, class:"btn btn-info btn-sm"} %>
                <%end%>
                <%if restaurant.liked_users.include?(current_user) %>
                <%= link_to "取消追蹤", unlike_restaurant_path(restaurant), {method: :post, class:"btn btn-secondary btn-sm"} %>
                <%else %>
                <%= link_to "追蹤", like_restaurant_path(restaurant), {method: :post, class:"btn btn-info btn-sm"} %>
                <%end%>
            </div>
          </div>
        </div>
        <div class="feeds-intro">
          <p>粉絲人數：<%= restaurant.rank %></p>
        </div>
      </div>
    <% end %> 
  </div>

  <div class="col-lg-4 col-sm-10">
    <h3>最新評論</h3>
    <% @recent_comments.each do |comment| %>
    <div class="feeds-block">
    <h4><%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %></h4>
    <p><%= comment.content %></p>
    <p>by <%= link_to comment.user.name, user_path(comment.user) %></p>
    </div>
    <% end %>
  </div>

</div>

app/views/restaurants/index.html.erb
	<div class="tab-bar">
		<ul class="nav nav-tabs nav-tabs-main">
  		<li class="nav-item">
  			<%= link_to "所有餐廳", restaurants_path, class: "#{cp(restaurants_path)} nav-link" %>
  		</li>
  		<li class="nav-item">
  			<%= link_to "餐廳分類", category_path(@categories.first), class: " nav-link" %>
  		</li>
  		<li class="nav-item">
  			<%= link_to "最新動態", feeds_restaurants_path, class: " nav-link" %>
  		</li>
  		<li class="nav-item">
        <%= link_to "美食達人", experts_restaurants_path, class: "nav-link" %>
      </li>
		</ul>
	</div>
	<%= render partial: "shared/restaurants" %>
	<div class="text-center margin-10-10">
		<%= paginate @restaurants, theme: 'twitter-bootstrap-4' %>
	</div>
	<div style="height:1px;"></div>

app/views/restaurants/show.html.erb
<section class="page-section clearfix z">
    <div class="intro">
      <%= image_tag(@restaurant.image, {alt: "image-not-found", onerror:"this.src='/image-not-found.jpg';", class:"intro-img img-fluid mb-3 mb-lg-0 rounded"}) %>
      <div class="intro-text left-0 text-center bg-faded p-5 rounded">
        <h2 class="section-heading mb-4">
          <span class="section-heading-lower"><%= @restaurant.name %></span>
        </h2>
        <p class="mb-3"><%= @restaurant.description %></p>
        <div class="intro-button mx-auto">
          <%if @favorite_check==:False %>
          <%= link_to "加入最愛！", restaurant_favorites_path(@restaurant), {method: :post, class:"btn btn-info btn-xl"} %>
          <%else %>
          <%= link_to "取消最愛！", restaurant_favorite_path(@restaurant, @favorite), {method: :delete, class:"btn btn-secondary btn-xl"} %>
          <%end%>
          <%if @restaurant.liked_users.include?(current_user) %>
          <%= link_to "取消追蹤！", unlike_restaurant_path(@restaurant), {method: :post, class:"btn btn-secondary btn-xl"} %>
          <%else %>
          <%= link_to "追蹤！", like_restaurant_path(@restaurant), {method: :post, class:"btn btn-info btn-xl"} %>
          <%end%>
        </div>
      </div>
    </div>
</section>

<section class="page-section cta margin-4" id="detail">
    <div class="row ">
      <div class="col-xl-9 mx-auto">
        <div class="cta-inner text-center rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-lower">Details</span>
          </h2>
          <p class="mb-0">Tel:<%= @restaurant.tel %></p>
          <p class="mb-0">Address:<%= @restaurant.address %></p>
          <p class="mb-0">Opening hours:<%= @restaurant.opening_hours %></p>
        </div>
      </div>
    </div>
</section>

  <div class="comments-outter">
    <div class="comments-outter-tittle">
      <i class="fa fa-comments fa-2x" aria-hidden="true">  Comments</i>
    </div>
    <% @restaurant.comments.each do |c| %>
    <div class="comment-box">
      <div class="comment-tittle">
        <p>Comment from: <%= c.user.email %> (<%=time_ago_in_words c.updated_at %>) </p>
        <% if current_user.admin? %>
        <%= link_to "Delete", restaurant_comment_path(@restaurant, c), {method: :delete, class:"btn"} %>
        <% end %>
      </div>
      <div class="comment-text">
        <%= c.content %>
      </div>
    </div>
    <% end %>
    <%= form_for [@restaurant,@comment] do |f| %>
    <div class="form-group comment-form">
      <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
      <%= f.submit class: "btn btn-primary" %>
      <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
    </div>
    <% end %>
  </div>