config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root"application#index"
  resources :restaurants, only: [:index, :show] do
  	resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    get :feeds, :on => :collection
    get :experts, :on => :collection
    member do
      post :like
      post :unlike
    end
  end
  resources :categories, only: [:show]
  resources :users, only: [:index, :show, :edit, :update]
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  namespace :admin do
  	resources :restaurants
  	resources :categories
  end

end

app/models/category.rb
class Category < ApplicationRecord
	validates_presence_of :name
	validates :name, uniqueness: true
	has_many :restaurants
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController

  def index
  	@categories = Category.all
	  if params[:id] #確認是否有id=?傳入網頁，因為是共用同一個submmit按鈕
	    @category = Category.find(params[:id])
	  else
	    @category = Category.new
	  end
  end

  def update
	  @category = Category.find(params[:id])
	  if @category.update(category_params)
	    redirect_to admin_categories_path
	    flash[:notice] = "category was successfully updated"
	  else
	    @categories = Category.all
	    render :index
	  end
	end

  def create
	  @category = Category.new(category_params)
	  if @category.save
	    flash[:notice] = "category was successfully created"
	    redirect_to admin_categories_path
	  else
	    @categories = Category.all #失敗時要把Categories回傳給index
	    render :index
	  end
  end

   def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:alert] = "category was successfully deleted"
    redirect_to admin_categories_path
  end


  private
  def category_params
  	params.require(:category).permit(:name)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		@categories=Category.all
		@category = Category.find(params[:id])
  	@restaurants = @category.restaurants.page(params[:page]).per(9)
	end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
  <div style="height: 1px;"> </div>
  <div class="margin-10-10">
  <%= link_to 'Restaurant', admin_restaurants_path %> |
  <%= link_to 'Categories', admin_categories_path %>
  </div>
  <div class="form-inline margin-10-10" >
  <%= form_for [:admin, @category] do |f| %>
    <div class="form-group margin-10-10">
      <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
    </div>
    <%= f.submit class: "btn btn-primary margin-10-10" %>
  <% end %>
  </div>
  <h1>餐廳分類總表</h1>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>#</th>
            <th>Category Name</th>
            <th>Numbers of</th>
            <th>Function</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <th scope="row"><%= category.id %></th>
            <td><%= category.name %></td>
            <td><%= category.restaurants.count %></td>
            <td>
              <%= link_to 'Edit', admin_categories_path(category) %>
              <%= link_to 'Delete', admin_category_path(category), method: :delete, data: { confirm: "Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>