config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root"application#index"
  resources :restaurants, only: [:index, :show] do
  	resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    get :feeds, :on => :collection
    get :experts, :on => :collection
    member do
      post :like
      post :unlike
    end
  end
  resources :categories, only: [:show]
  resources :users, only: [:index, :show, :edit, :update]
  resources :followships, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  namespace :admin do
  	resources :restaurants
  	resources :categories
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	validates_presence_of :name
	validates :name, uniqueness: true
	has_many :restaurants
end

app/models/comment.rb
class Comment < ApplicationRecord
	validates_presence_of(:content)
	belongs_to :restaurant
	belongs_to :user
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :restaurant
	validates :user_id, uniqueness: { scope: :restaurant_id }
end

app/models/followship.rb
class Followship < ApplicationRecord
	belongs_to :user
  belongs_to :following, class_name: "User" 
  #followship裡面有個following id，但沒有following這個model，所以要用class_name把這個id指向USER model
  validates :following_id, uniqueness: { scope: :user_id }
  #驗證同樣的following_id 如果有同樣的user_id就不能存入 #validates :name, uniqueness: true
  

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :restaurant
	validates :user_id, uniqueness: { scope: :restaurant_id }
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	validates_presence_of(:name,:tel,:address,:opening_hours)
	mount_uploader :image, PhotoUploader
	belongs_to :category
	#喜歡、收藏餐廳 （刪除餐廳時會刪除喜歡的紀錄）
	has_many :favorites, dependent: :destroy
	#留言
	has_many :comments, dependent: :destroy
	#喜歡
	has_many :likes, dependent: :destroy
	has_many :liked_users, through: :likes, source: :user

	def rank_count
		#rank由 favorite 跟 like 相加，之後也可以加入comment
		count=self.favorites.size
		count=count+self.likes.size
		#count=count+self.comments.size
		self.rank=count
		self.save
	end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  validates :email, uniqueness: true

  #留言
  has_many :comments, dependent: :destroy
  has_many :commented_restaurants, through: :comments, source: :restaurant
  #最愛、收藏
  has_many :favorites, dependent: :destroy
  #透過收藏 取得餐廳 User.restarants
  has_many :restaurants, through: :favorites
  #喜歡
  has_many :likes, dependent: :destroy
  has_many :liked_restaurants, through: :likes, source: :restaurant
  #使用source更名，可以直接讀取 User.liked_restaurants

  has_many :followships, dependent: :destroy
  has_many :followings, through: :followships 
  #指回following，user.following指這個user正在追蹤的人(following)

  #follower 可以從user取得 追蹤自己的人(follower)
  has_many :inverse_followships, class_name:"Followship", foreign_key:"following_id"
  has_many :followers, through: :inverse_followships, source: :user
  #先自建一個inverse followships，指定followship model的following_id (對USER來說 USER是PK，指去followship的FK是following_id)

  mount_uploader :avatar, AvatarImageUploader

  def admin?
   	self.role == "admin"
  end
  def has_following?
    self.comments.size >0
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if:  :devise_controller?
  before_action :authenticate_user!

  def index
    redirect_to restaurants_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :intro, :avatar])
  end

  def authenticate_admin
  	unless current_user.admin?
  		flash[:alert]="非管理員(Not Allow!)，redirect_to root_path"
  		redirect_to root_path  		
  	end
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def show
		@categories=Category.all
		@category = Category.find(params[:id])
  	@restaurants = @category.restaurants.page(params[:page]).per(9)
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.new(comment_params)
    @comment.restaurant = @restaurant
    @comment.user = current_user
    if @comment.save
      flash[:notice] = "Comment新增成功"
      redirect_to restaurant_path(@restaurant)
    else
      redirect_to request.referrer, alert: "Comment不得為空白"
    end
  end

  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])

    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
		@restaurant=Restaurant.find(params[:restaurant_id])
		@favorite=Favorite.new()
		@favorite.user_id=current_user.id
		@favorite.restaurant_id=@restaurant.id
		@favorite.save!
		@restaurant.rank_count
		redirect_back(fallback_location: root_path)
	end
	def destroy
		@restaurant=Restaurant.find(params[:restaurant_id])
		@favorite=Favorite.where(:restaurant_id => @restaurant.id, :user_id => current_user.id )
		@favorite.destroy_all
		@restaurant.rank_count
		redirect_back(fallback_location: root_path)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


	def show
		@user=User.find(params[:id])
		@commented_r=@user.commented_restaurants.uniq
		@followings=@user.followings
		@followers=@user.followers
	end

	private
	def check_user #把edit功能併進去devise 就不用這個功能了
		if User.exists?(:id => params[:id])
			if current_user != User.find(params[:id])
		 		redirect_to root_path, alert: "Dont do things illegal"
		 	end
		else
			redirect_to root_path, alert: "Dont do things illegal"
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def cp(path)
  "active" if request.url.include?(path)
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/restaurant_helper.rb
module RestaurantHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="zh-Hant-TW">
  <head>
    <title>RProject</title>
    <meta http-equiv="Content-Language" content="zh-Hant-TW">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- NAV: https://startbootstrap.com/template-overviews/landing-page/ (bootstrap4 version) -->
    <nav class="navbar navbar-light bg-light static-top">
      <div class="container">
        <%= link_to('Best Restaurant', root_path, {class: "navbar-brand"}) %>
        <div class="navbar-right">
        <% if current_user %>
            <a heref="#">Hi, <%= current_user.email%></a>
            <%= link_to('個人檔案', user_path(current_user), {class: "btn btn-outline-secondary"}) %>
            <%= link_to('修改資料', edit_user_registration_path, {class: "btn btn-outline-secondary"}) %>
            <%= link_to('登出', destroy_user_session_path, {method: :delete, class: "btn btn-outline-secondary"}) %>
        <% else %>
            <%= link_to('註冊', new_user_registration_path, {class: "btn btn-outline-secondary"}) %>
            <%= link_to('登入', new_user_session_path, {class: "btn btn-outline-secondary"}) %>
        <% end %>
        <% if current_user && current_user.role == "admin"%>
            <%= link_to '後台', admin_restaurants_path, {class: "btn btn-primary"} %>
        <% end %>
        </div>
      </div>
    </nav>


    
    <div class="container bgc-white">
        <% if flash[:notice] %>
    <div class="container">
        <div class="row">
            <div class="alert alert-success alert-dismissible" role="alert">
                <div class="alert_mes"><%= notice %></div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
        </div>
    </div>
    <% end %>
  
    <% if flash[:alert] %>
    <div class="container">
        <div class="row">
            <div class="alert alert-danger alert-dismissible" role="alert">
                <div class="alert_mes"><%= alert %></div>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
        </div>
    </div>
    <% end %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_restaurants.html.erb
	<div class="row">
	<% @restaurants.each do |r| %>
    <div class="col-lg-4 col-sm-6 portfolio-item">
      <div class="card h-100">
        <div class="card-pic-width">
          <div class="card-pic-height">
            <%= link_to image_tag(r.image, {alt: "image-not-found", onerror:"this.src='/image-not-found.jpg';", class: "card-picture"}), restaurant_path(r), {class: "card-pic-position"} %>
            <span class="badge badge-secondary badge-position" style="font-size: 15px;"><%=r.category.name%></span>
          </div>
        </div>
        <div class="card-body">
          <h4 class="card-title">
            <p class="card-text"><%= r.name %></p>
          </h4>
          <p class="card-text"><%= r.description %></p>
        </div>
      </div>
    </div>
    <% end %>
  </div>